### ISSUE TITLE
Support for Functions or don't generate source code

### ISSUE THREAD

**Issue by rjahn** [karsany/obridge#21]
OBridge creates function calls, e.g. for:

```
create or replace function execFunction(pNumber in out number, pInText in varchar2, pOutText out varchar2) return varchar2 is
  res varchar2(200);
  nr number := pNumber;
begin
  pOutText := 'Out: '|| pOutText ||' In: '|| pInText;

  pNumber := pNumber + pNumber;

  return 'IN-Param Nr: '|| nr;
end execFunction;
```

But the generated code:

```
CallableStatement ocs = connection.prepareCall(                "" +
                        "DECLARE " +
                        "BEGIN " +
                        "  \"EXECFUNCTION\"( " +
                        "    \"PNUMBER\" => :PNUMBER" +
                        "   ,\"PINTEXT\" => :PINTEXT" +
                        "   ,\"POUTTEXT\" => :POUTTEXT" +
                        "   );" +
                        "END;" +
                        "");
```

doesn't work because it doesn't recognize the return value. And you don't support OUT parameter in your call!

Simply ignore functions and OUT parameter functions/procedures, because your project description:

> code generator for calling Oracle PL/SQL package procedures

doesn't contain functions - or support both :)

**Comment by karsany** [comment]
Thank you for your finding. I'll fix it - not with ignoring functions.
You are the first bug reporter - who is not me. :)

**Comment by rjahn** [comment]
Cool!

I tried to check the typesafety :) because we have a generic solution for the same problem in our OS framework JVx.We do following to call a function with in and out params:

```
OutParam ouTextParam = new OutParam(InOutParam.SQLTYPE_VARCHAR);
Object oResult = dba.executeFunction("execFunction", Types.VARCHAR, BigDecimal.valueOf(25), "Hello JVx' ", ouTextParam);
```

I'm also interested in your solution for the BOOLEAN problem :)
Here's our solution: http://blog.sibvisions.com/2015/12/18/using-boolean-datatype-with-oracle-and-jdbc/

My idea was a short blog post about obridge and the usage together with JVx.

**Comment by karsany** [comment]
OBridge uses sys.diutil.bool_to_int and sys.diutil.int_to_bool calls for converting between boolean and null/0/1.

Booleans are converted to number in java then to boolean in plsql then back to number and from number to boolean in java, back again.

Not a straightforward thing, but this was the best workaround I found.

**Comment by rjahn** [comment]
:) we have the same implementation.

**Comment by karsany** [comment]
New test case added, issue fixed.
Functions not in a package are working.

**Comment by karsany** [comment]
Snapshot version: http://obridge.org/snapshots/obridge-1.2-SNAPSHOT-20160226.jar

**Comment by rjahn** [comment]
Tested: works.

2 Thumbs up.

**Comment by karsany** [comment]
@rjahn thank you for the blog post
http://blog.sibvisions.com/2016/02/26/use-obridge-together-with-jvx/

**Comment by rjahn** [comment]
With pleasure.
